[color_scheme]
active = "ayu-mirage"

[font]
family = "JetBrains Mono"
size_px = 20.0
weight = "Regular"
style = "Normal"
line_height = 1.2
ligatures = true

[indent]
type = "spaces"
width = 2
tab_width = 2
detect = true

[view]
line_numbers = true
highlight_current_line = true

[cursor]
blink = true
blink_rate_ms = 500
